FROM python:3.10.16-slim

WORKDIR /app

# Copy and install dependencies
COPY requirements-streamlit.txt .
RUN pip install --upgrade pip && pip install -r requirements-streamlit.txt

# Copy model file and application code
COPY forecasting_model.pkl .
COPY . .

EXPOSE 8501

CMD ["streamlit", "run", "streamlit.py", "--server.port", "8501", "--server.address", "0.0.0.0"]